name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Select a tag"
        required: true
        default: "BestSeller"
        type: choice
        options:
          - "BestSeller"
          - "Regression"
          - "Shoppingcart"
          - "ShoppingToCart"

jobs:
  build:
    runs-on: cicdbestseller

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Display Selected Tag
      run: echo "Selected Tag: ${{ github.event.inputs.tag }}"
    - name: Build and Test with Maven
      run: mvn clean test -Ddataproviderthreadcount=3 -Dcucumber.filter.tags="@${{ github.event.inputs.tag }}"
